version: '3.8'

services:
  postgres:
    container_name: kyzmatapp_pg
    image: postgres:16.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5051:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin4:
    container_name: kyzmatapp_pgadmin
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kadyrov.atan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "5050:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin:
